### STAGE 1: Build ###
FROM node:16.15-slim as build
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json
RUN npm cache clean --force
RUN npm install

COPY ./public ./public
COPY ./src ./src
COPY .env .env
# RUN grep -oP 'REACT_APP_VERSION=\K.+' .env | tr -d '\n' > ./public/version.cfg

RUN npm run build

# ### STAGE 2: Production Environment ###
FROM nginx:alpine

ENV NODE_ENV production

RUN apk add --no-cache tzdata
ENV TZ America/Bahia

# COPY --from=build /app/build /var/www/poupatize
COPY --from=builder /app/public ./poupatize/public
COPY --from=builder /app/.next/standalone ./poupatize
COPY --from=builder /app/.next/static ./poupatize/.next/static

COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
