apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-ofertas-poupatize
  namespace: poupatize
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: gilvan.souza@efabrika.com.br
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-ofertas-poupatize
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-ofertas-poupatize #example-com
  namespace: poupatize
spec:
  secretName: letsencrypt-ofertas-poupatize-tls
  issuerRef:
    name: letsencrypt-ofertas-poupatize
  commonName: ofertas.poupatize.com.br
  dnsNames:
  - ofertas.poupatize.com.br
